### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by potocpav** [chwba/concur_gui_test#1]

**Comment by potocpav** [comment]
Could you describe your use-case in more detail? What exactly are you trying to achieve?
It would really help me help you :)

Please describe desired semantics in more detail. What should happen, if user starts another computation if one is already in progress? Should user be able to cancel running computations? Are the computations long-running, should there be a progress bar in the future?

If you describe what your app is for, it may be easier to communicate the features you need to achieve that.

**Comment by potocpav** [comment]
I think it is quite common to have a single "global" ThreadPoolExecutor, running for the whole duration of the application. In that case, you don't need to call shutdown() at all. Is there a problem with that approach?

**Comment by chwba** [comment]
the problem with a global TPE is that the resources, that have been assigned to them upon submit are not being freed without calling shutdown. you can verify this by clicking the thread button i have created, it will  output what activeCount() returns.

**Comment by potocpav** [comment]
OK I see. So a click in the dialog window spawns ~1000 threads, which can each be monitored & stopped in the application. Should it then be possible to spawn another 1000 threads, before the original batch finishes? All the stuff would then run concurrently?

**Comment by chwba** [comment]
Correct. Well one feature would probably run at a time, so say I start feature 1, then it wouldnt make sense to start feature 1 again. but I could start  feature 2 for instance so yeah there would be concurrency.

**Comment by potocpav** [comment]
If there should be N tasks in M threads (1000 tasks in 100 threads), then to avoid dirty hacks, a custom `ThreadPoolExecutor` should IMO be implemented, with thread killing support. 

If that is not the case, and you want 1000 tasks in 1000 threads  (task is a thread), then it is simpler, as there do not need to be any task queues, inter-thread synchronization, etc.

I quite enjoy doing this kind of stuff, so I will try to implement either. Which one do you need?

**Comment by chwba** [comment]
> If there should be N tasks in M threads (1000 tasks in 100 threads), then to avoid dirty hacks, a custom ThreadPoolExecutor should IMO be implemented, with thread killing support.
Please clarify, what you mean by task. As of now one thread will have a fixed workflow it will perform. Simple example: -> Connect to the API -> Do some stuff with the API -> Log some information -> Exit the thread. The running threads dont have to communicate with each nor are dependant from each other in any way if thats what you mean.

>If that is not the case, and you want 1000 tasks in 1000 threads (task is a thread), then it is simpler, as there do not need to be any task queues, inter-thread synchronization, etc.
If my above explanation is correct, then indeed its 1000 tasks in 1000 threads without inter-thread communication/task queries or synchronisation. 

>Edit: It seems your task is probably simpler than I thought. You just need to be able to kill the whole threadpool at once, right? Not separate threads. In that case, your original approach of having a thread with a threadpool is probably the way to go.

In case of canceling a feature, this would be correct. In case of a running feature, it just has to wait for all the threads that are still doing work (my code will take care, that all threads that have been submitted will either finish successfully or quit the thread sith sys.exit().) My problem was, that I could not get it, that the actual resources of the submitted threads will be freed after completion. (Clicking the button running threads shows 21 threads even after the threads are finished)

**Comment by potocpav** [comment]
I implemented a threading show-case. Hopefully, I captured your use-case well. If not, and the behavior should be different, please specify your needs the best you can :)

I used `multiprocessing` for features, because AFAIK it is the only way to correctly implement non-cooperative task cancellation. I don't think threads in Python can be safely terminated.

I also commented out logging, because I was not sure how it should look.

**Comment by chwba** [comment]
Quick question, how can I make this one work with concur?
https://github.com/ocornut/imgui/issues/933

**Comment by potocpav** [comment]
Is it maybe OK to ship an `imgui.ini` file with the application, where the window positions & docking are preset?

Having a programmatic way to dock windows (or set defaults) would be cool I guess. I didn't look into how that stuff is implemented in ImGui though.

**Comment by chwba** [comment]
If it works with the imgui.ini, that would be perfectly fine, how would I have to configure it for that?

**Comment by chwba** [comment]
Meanwhile im proceeding further to implement new GUI parts of the applications.
Im currently looking for how to implement the following features:
* Popups
* Outputing logs, for each running featurelike here: https://cloud.githubusercontent.com/assets/872946/16177124/c06bdcfa-3624-11e6-9cab-f2bb34ad4345.png with the difference, that the log should be attached to each running feature, basically just below the Threading showcase
* Add a possibility to collapse, the running threads list

**Comment by potocpav** [comment]
> If it works with the imgui.ini, that would be perfectly fine, how would I have to configure it for that?

It should be automatic. If you close an application, the windows are restored in the same position and dock-state automatically, through imgui.ini.

**Comment by chwba** [comment]
Yes, thank you, what I mean is when we ship the application to the client and he first opens it, it would be nice to have all the windows docked, I guess it will work if I just dock them once and then ship the imgui.ini it has created on my machine, ill test.

**Comment by potocpav** [comment]
That's what I had in mind. I am playing with your code right now, some improvements are already implemented.

You are developing the application with a different user-interface in mind than what I was doing when using Concur. Some of the things you are trying to achieve (a popup warning on button click) are quite awkward to do.

I think Concur itself should be improved as you develop the application. For example, the popup-based input validation may be a common pattern in many application, so a direct support may be worth it. I will look into that.

In the meantime, my solutions to your problems may be quite hack-ish :)

**Comment by chwba** [comment]
Im super happy with your help, as I had said in the beginning, I wanted to implement pyimgui for a long time already, finally I can realize it.

**Comment by potocpav** [comment]
If you can abstract out any patterns, and open PRs against Concur, that would of course be great :) I don't know if you already have enough knowledge about the internals to do that.

**Comment by chwba** [comment]
I would love to but I really think I havent digged deep enough into concurs internals yet. What I can do is give you all the gui parts of my application, that I am creating, so you will have a really complex example.

**Comment by potocpav** [comment]
I added all the stuff you wanted, I think.

Logging is in a separate window, which may or may not be what you want. The separate window can be docked to the bottom of a Feature window, which is what you wanted.

**Comment by chwba** [comment]
You are really deep into this gui, nice speed :)
I think I managed to crash it, try with this imgui.ini:
```
[Window][Default##Concur]
Pos=0,0
Size=1278,846
Collapsed=0

[Window][Background Window]
Pos=0,0
Size=1278,846
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Nice Feature]
Pos=141,110
Size=400,300
Collapsed=0

[Window][Feature 1]
Pos=74,119
Size=717,475
Collapsed=0
DockId=0x00000001,0

[Window][Feature 2]
Pos=855,213
Size=558,495
Collapsed=0

[Window][Feature 1 Log]
Pos=146,121
Size=718,154
Collapsed=0
DockId=0x00000001

[Docking][Data]
DockNode  ID=0x00000001 Pos=74,119 Size=717,475 Selected=0x3236C0CA
DockSpace ID=0x8B594EFD Window=0x1D90FC2A Pos=0,19 Size=1278,827 CentralNode=1
```
Made a screencast: https://nextcloud.mnwd.in/s/6d7LN9MfMEt4j9d

**Comment by potocpav** [comment]
Your implementation of pop-up didn't work because the code inside `begin_popup` and `end_popup` must be called in every frame, not just in the one frame when the button was clicked.

And regardless, all UI code must be drawn inside the `yield from` block, not inside event handlers. Creating a new Concur widget, as I did, to wrap all the ImGui UI calls is the cleanest solution.

**Comment by chwba** [comment]
>Your implementation of pop-up didn't work because the code inside begin_popup and end_popup must be called in every frame, not just in the one frame when the button was clicked.

>And regardless, all UI code must be drawn inside the yield from block, not inside event handlers. Creating a new Concur widget, as I did, to wrap all the ImGui UI calls is the cleanest solution.

Understood, makes sense

**Comment by chwba** [comment]
I just deleted the old imgui.ini, now it works perfectly, I guess the old values caused it to crash and if i understand it correclty, it can now not get corrupted again.

**Comment by potocpav** [comment]
About the crash: I created a `window` inside a `window` to save a bit of indendation. not a good idea. Fixed.

**Comment by chwba** [comment]
Unlucky :D. Alright ill restructure it all a little, add some classes and then point out another thing.

**Comment by potocpav** [comment]
> It would be better if the logging would not be in a separate window. I think it would be best if it was "hard-attached" to each feature (there will many different features).

I would leave this for later. It is possible to do, for sure, but not necessary in the prototype phase.

**Comment by chwba** [comment]
Alright, did a number of changes and restructs. When all features are maximized, I did not find a way to attach the log of each feature, to the feature itself only, instead it would display a tabbed view of every feature below, thats quite confusing for the user, maybe I was just not smart enough to move the GUIs correctly?

**Comment by potocpav** [comment]
> When all features are maximized, I did not find a way to attach the log of each feature, to the feature itself only, instead it would display a tabbed view of every feature below,

I think that is an inherent thing for maximized windows. To fix this, it is necessary to merge the two windows. It should be ~2 lines of code if resizing the logging window isn't necessary. Try wrapping all the window contents _apart_ from the logging widget inside a `child_window`. Use "smart" dimensions dimensions [documented here](https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html#imgui.core.begin_child). 

> when all windows are maximized and I start the app, it will always focus the window on the very right side, even if I had selected the window on the left side on exit, is there a way to manage this behaviour?

This is probably a bug in ImGui. It may be possible to solve just by upgrading ImGui, since an old version is used in Concur/PyImGui. IDK if they fixed it yet in ImGui, but is seems too obvious *not* to be fixed.

**Comment by potocpav** [comment]
I checked, and upgrading ImGui didn't help. Here is the issue about the tab focus: https://github.com/ocornut/imgui/issues/2304

**Comment by chwba** [comment]
Alright, ill tinker around with all of this and see what I can achieve. I put a couple minor TODOs in the code, that I couldnt figure out.

**Comment by chwba** [comment]
I made the whole thing a bit more generic now and made actual use of inheritance. When you find some time, take a look at the TODOs I put in the code, that I still couldnt figure out how to realize. Also  do you know of a way to have a "Main Log", which could fetch messages cross running features,  this one is not as important as colored log outputs but would be nice to have.

**Comment by potocpav** [comment]
I don't know anything about Python logging, I heard of it first time here. So I can't help you with the main log. About the unicode support, from cursory research it seems that ImGui supports that. You just need to research how that's done.

**Comment by potocpav** [comment]
I addressed all the other issues in commits & comments. Feel free to delete the comments once you read them.

By and large, what you wanted is possible to do in ImGui because of its flexibility. Concur just does control flow using generators. Other than that, it is a thin wrapper on top of PyImGui. So the "raw" PyImGui calls can be used without a problem.

I tried to write in the comments how I arrived at the solution, so you can do that too in the future :)

**Comment by potocpav** [comment]
About the chinese characters. This works:

```python
import concur as c
import imgui


font_name = "ArialUni.ttf"
imgui.create_context()
io = imgui.get_io()
font = io.fonts.add_font_from_file_ttf(font_name, 20, glyph_ranges=io.fonts.get_glyph_ranges_chinese())
c.main(c.font(font, c.text("Hello, world! 菜单在哪里文件我是中文")))
```

Your font didn't seem to contain chinese characters. You can test with [this one](https://github.com/kaienfr/Font/blob/master/font/ARIALUNI.TTF).

**Comment by chwba** [comment]
Man, boss, thats supreme.  Everything works perfectly. Now I could also write a handler that will create a custom popup based on user input and settings which is either continueable or not, really cool. Also now could make the input fields size adjust dynamically. Glyph ranges also works perfectly, tested with cyrillic.

Will now try to figure out the colored logging and the line wrapping in the log window, in case a line is super long and doesnt fit even if maximized.

**Comment by potocpav** [comment]
glad you like it :)

**Comment by chwba** [comment]
quick question: which packages do we need to ship? concur and concur-imgui or imgui itself aswell?
https://pypi.org/project/concur-imgui/
https://pypi.org/project/imgui/
https://pypi.org/project/concur

**Comment by potocpav** [comment]
Sorry for late reply - vacation. What do you mean  by "to ship"? Normally I just specify the dependency "concur" inside "setup.py".

**Comment by chwba** [comment]
Vacation is good bro, hope you enjoyed it, yes thats exactly what I wanted to know thanks! Currently I'm working a lot on the main app. Once I get to the point where I find that I will leave it this way I will integrate all the code and optimizations I did to this repo as well.

**Comment by chwba** [comment]
Is there a way to get code-completion for imgui-functions, when working with concur? As far as I understand concur, it ships a CPP version of imgui, but that of course doesnt offer code completion from within the IDE. - Before I had just manually installed imgui additionally but I don't think thats a clean approach, have you got an advice for this one?

Also If I call imgui directly for something like `c.lift(lambda: imgui.push_item_width(self.evaluate_field_size(self.input)))`, would it be correct to do `from concur import imgui` or `import imgui`?

**Comment by potocpav** [comment]
I don't know anything about code-completion since I don't use it. But "concur-imgui" is just a fork of "imgui" with some minor changes, so it shouldn't matter which one is used? IDK. The PyImGui functions are defined in Cython, and they call the C++ ImGui functions which are named differently (InputText vs. input_text for example).

About the ImGui import, I have always used just `import imgui`. It is up to the user to install the forked "imgui".

```sh
$ pip list | grep imgui
concur-imgui             1.3.4
```

**Comment by potocpav** [comment]
Did you make any interesting progress with the application?

**Comment by chwba** [comment]
With the tools you gave me im currently working on its base and on connecting everything to it, im almost done.

**Comment by chwba** [comment]
Im getting closer to the finish line, 2 questions:
1. For some reason, when I write a '?' in any text field it crashes with:
`TypeError: ord() expected a character, but string of length 2 found`
2. What would be the smartest way, to display the user a "Login" window, before the main app starts?  My first idea is to just  run another c.main() for this with just the login window and after that quit that c.main() and start a new one with the actual app but maybe you have a better idea?

**Comment by chwba** [comment]
I fixed the '?' issue by altering the PatchedGlfwRenderer as follows:

```python
class PatchedGlfwRenderer(GlfwRenderer):
    """ Custom variant of Glfwrenderer in PyImGui:

    https://github.com/swistakm/pyimgui/blob/master/imgui/integrations/glfw.py

    This works around the issue that GLFW uses EN_US keyboard to specify the key codes
    in `keyboard_callback`. This meant that keyboard shortcuts were broken on non-querty
    keyboard layouts. 
    
    With this change it also works around the issue if the keyname consists of two letters,
    such as ß (SS) on Germany keyboards

    See https://github.com/ocornut/imgui/issues/2959 for details.
    """
    def keyboard_callback(self, window, key, scancode, action, mods):
        if key < 0x100:
            # Translate characters to the correct keyboard layout.
            key_name = glfw.get_key_name(key, 0)
            if key_name is not None:
                key = ord(key_name.upper() if len(key_name.upper()) == 1 else "?")
        super(PatchedGlfwRenderer, self).keyboard_callback(window, key, scancode, action, mods)
```

**Comment by chwba** [comment]
Man I just found your `colors.xkcd_colors`, thats insane haha so nice

**Comment by potocpav** [comment]
Thanks for the bug report. I will look into it, but I am quite busy right now.

`colors.xkcd_colors` is insane. I am open to swapping it for something more serious :)

**Comment by chwba** [comment]
Its great actually and works just fine :D, ill push more to the repo when I find the time.

**Comment by chwba** [comment]
Found another key-combination, that will crash it, at least on a german keyboard "ALT +PRNT" drops invalid scancode.

I workarounded like this for now:
```python
class PatchedGlfwRenderer(GlfwRenderer):
    """ Custom variant of Glfwrenderer in PyImGui:

    https://github.com/swistakm/pyimgui/blob/master/imgui/integrations/glfw.py

    This works around the issue that GLFW uses EN_US keyboard to specify the key codes
    in `keyboard_callback`. This meant that keyboard shortcuts were broken on non-querty
    keyboard layouts.

    With this change it also works around the issue if the keyname consists of two letters,
    such as ß (SS) on Germany keyboards

    See https://github.com/ocornut/imgui/issues/2959 for details.
    """
    def keyboard_callback(self, window, key, scancode, action, mods):
        print(window,key,scancode,action,mods)
        if scancode in [56, 84]:
            return
        if key < 0x100:
            # Translate characters to the correct keyboard layout.
            key_name = glfw.get_key_name(key, 0)
            if key_name is not None:
                key = ord(key_name.upper() if len(key_name.upper()) == 1 else "?")
        super(PatchedGlfwRenderer, self).keyboard_callback(window, key, scancode, action, mods)
```

**Comment by potocpav** [comment]
Thanks for the bug reports. I was not able to fully replicate the issue: "?", and ALT+PRNT works here, but ß doesn't. 

What are the scancodes `[56, 84, 256]` that you are ignoring?

**Comment by chwba** [comment]
Sorry for the late reply. I believe it is because on German keyboards the ß is on the same key with ?
Here are the results with a German keyboard:

ALT+PRNT -> `glfw.GLFWError: (65540) b'Invalid scancode'`
ß -> `TypeError: ord() expected a character, but string of length 2 found` (Key: 45, Scancode: 12, Action:1, Mods: 0)
Shift + ß (which creates '?') on a German keyboard -> `TypeError: ord() expected a character, but string of length 2 found`
Mediakey Next/Previous Song/Play/Stop/Volume up/Volume Down ->  `glfw.GLFWError: (65540) b'Invalid scancode'` (Key: -1, Scancode: 256, Action: 1, Mods: 0)
FN-Key + any key, that will not create a valid combination, e.g. FN-Key + A -> `TypeError: keyboard_callback() missing 1 required positional argument: 'mods'` (Key: 50, Scancode: 3, Action: 1, Mods: 0)

In fact now I have to reboot my machine, because it will drop `TypeError: keyboard_callback() missing 1 required positional argument: 'mods'` on any key I press. Keyboard used: HyperX Alloy Origins.

**Comment by chwba** [comment]
Just want to let you know, that finally I am getting closer to release of my app. Currently im trying to realize two things:

1. I have the log-widget and am trying to make activate tailing/autoscroll for it.
2. I would like to make it, so one can copy something out of the widget
3. Trying to create a separate window, that can be opened on demand which will create a graph based on proxy response times

And some more minor things, do let me know if you have some spare time, then I would demonstrate you how the app currently looks and show you the source of it via AnyDesk/TeamViewer session.

**Comment by chwba** [comment]
bump

**Comment by chwba** [comment]
Im for instance trying to create a `v_slider_float` I get:
`imgui.core.ImGuiError: ImGui assertion error ((flags == 1 || (flags & ImGuiSliderFlags_InvalidMask_) == 0) && "Invalid ImGuiSliderFlags flag!  Has the 'float power' argument been mistakenly cast to flags? Call function with ImGuiSliderFlags_Logarithmic flags instead.") at imgui-cpp/imgui_widgets.cpp:2754`

I call it via:

```python
c.interactive_elem(imgui.v_slider_float,
                   name="SLIDER_FLOAT",
                   width=20.0, height=100, value=1.0,
                   min_value=1, max_value=10,
                   format="%0.3f",
                   tag='my_tag'),
```

**Comment by chwba** [comment]
Also the autoscroll feature, we have built into the log widget doesn't work anymore.

**Comment by chwba** [comment]
This one is getting too big, ill create a new issue and do some cleanup.
